# Generated by Django 5.1.11 on 2025-09-18 01:34

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ttype', models.IntegerField(choices=[(1, 'Artist'), (2, 'Character'), (3, 'Series')])),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=main.models.rename_image)),
                ('uploadt', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='main.tag')),
            ],
        ),
    ]
