# Generated by Django 5.1.11 on 2025-09-18 00:45

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='tag',
            field=models.ManyToManyField(to='main.tag'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(upload_to=main.models.rename_image),
        ),
    ]
