# Generated by Django 5.1.11 on 2025-09-18 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='title',
        ),
    ]
