# Generated by Django 5.1.11 on 2025-10-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_artwork_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='artwork_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
