# Generated by Django 5.1.11 on 2025-09-18 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_artwork_tag_alter_artwork_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='tag',
            new_name='tags',
        ),
    ]
