# Generated by Django 5.1.11 on 2025-10-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tag_artwork_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='score',
            field=models.BigIntegerField(default=0),
        ),
    ]
