# Generated by Django 5.1.13 on 2025-10-23 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_artwork_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtype', models.IntegerField(choices=[(1, 'Upvote'), (-1, 'Downvote')])),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='main.artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('artwork', 'user')},
            },
        ),
    ]
